spring:
  profile.active: dev test prod
  datasource:
    url: jdbc:mysql://${AZMYSQL_HOST}/vollmed
    username: ${AZMYSQL_USER}
    password: ${AZMYSQL_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET}
